[MODE]
IsTraining = False
IsEvaluating = True

[DIRECTORY]
TrainingXPath = ../spatiotemporal_improved/demo/1_training_x
TrainingYPath = ../spatiotemporal_improved/demo/1_training_y
ValidationXPath = ../spatiotemporal_improved/demo/1_validation_x
;/1_validation_x_1.npy
ValidationYPath = ../spatiotemporal_improved/demo/1_validation_y
;/1_validation_y_1.npy
TestGTPath = ../spatiotemporal_improved/demo/1_db_demo.npy
TestQPath = ../spatiotemporal_improved/demo/1_q_demo.npy
TopKIDPath = ../spatiotemporal_improved/demo/1_topk_id.npy
TopKWeightsPath = ../spatiotemporal_improved/demo/1_topk_weight.npy
OutputDirectory = ./MODEL_OUT

[TRAINING]
ModelPath = ./MODEL_OUT/check/cp.h5
BatchSize = 128
TripletMargin = 0.5
Epochs = 100
Patience = 3
LossWeights = [1,1,1]

[MODEL]
GRUCellSize = 256
NumGRULayers = 3
GRUDropoutRatio = 0.3
EmbeddingSize = 256
EmbeddingVocabSize = None
TrajReprSize = 256
nums_head = 8
Bidirectional = True 
UseAttention = True 

[PREDICTION]
KS = [1, 5, 10, 50]
PredictBatchSize = 128
UseMeanRank = True 

[GPU]
GPUUsed = [2]
GPUMemory = 15000

